namespace: lang-learn

minio:
  enabled: true

  rootUser: minioadmin
  rootPassword: minioadmin

  mode: standalone

  persistence:
    enabled: true
    size: 30Gi
    storageClass: "microk8s-hostpath"

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

    limits:
      memory: 1Gi
      cpu: 500m

  buckets:
    - name: dvc-store
      policy: none
      purge: false

  service:
    type: ClusterIP
    port: 9000

  consoleService:
    type: ClusterIP
    port: 9001

  metrics:
    serviceMonitor:
      enabled: false
