"""Async generators for Goethe A2 Exam Teile (Lesen & Schreiben).

Architecture:
- Hybrid Lesen: Certified authentic texts / directories / ads from Redis TextPool,
  with questions dynamically generated by the external Metal-accelerated Gemma 4 E4B LLM.
- Schreiben: Dynamically generated by the external Metal-accelerated Gemma 4 E4B LLM
  with pool fallback.
"""
from __future__ import annotations

import asyncio
import collections
import json
import logging
import random
import re
from typing import Any, Dict, List, Tuple

from ..prompts import load_prompt
from ..backends.external_llama_backend import generate_external
from .text_pool import TextPool

logger = logging.getLogger("lang_learn.exam.generators")

# Singleton text pool instance
_text_pool: TextPool | None = None


def _get_text_pool() -> TextPool:
    global _text_pool
    if _text_pool is None:
        _text_pool = TextPool()
        stats = _text_pool.seed_pool()
        logger.info("Text pool initialized: %s", stats)
    return _text_pool


# Schreiben ring buffers for anti-repeat fallback
_recent_pool_history: Dict[str, collections.deque] = {
    "schreiben_t1": collections.deque(maxlen=4),
    "schreiben_t2": collections.deque(maxlen=4),
}


def _pick_distinct_pool_item(pool: List[Dict[str, Any]], key: str) -> Dict[str, Any]:
    history = _recent_pool_history.setdefault(key, collections.deque(maxlen=max(1, len(pool) - 1)))
    available_indices = [i for i in range(len(pool)) if i not in history]
    if not available_indices:
        history.clear()
        available_indices = list(range(len(pool)))
    choice_idx = random.choice(available_indices)
    history.append(choice_idx)
    return pool[choice_idx]


# ---------------------------------------------------------------------------
# JSON parsing & normalization helpers
# ---------------------------------------------------------------------------

def _repair_json_string(text: str) -> str:
    """Repair common JSON formatting errors from LLMs."""
    text = re.sub(r':\s*(?!")([A-ZÄÖÜa-zäöüß][^",}\]]*?")', r': "\1', text)
    text = re.sub(r',\s*([\}\]])', r'\1', text)
    return text


def _try_parse_json(text: str) -> Any | None:
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return None


def _extract_json(text: str) -> Any | None:
    """Robustly extract and parse JSON from LLM output."""
    if not text or not text.strip():
        return None

    cleaned = text.strip()
    cleaned = re.sub(r"^```(?:json|JSON)?\s*\n?", "", cleaned)
    cleaned = re.sub(r"\n?\s*```\s*$", "", cleaned)
    cleaned = cleaned.strip()

    result = _try_parse_json(cleaned)
    if result is not None:
        return result

    repaired = _repair_json_string(cleaned)
    result = _try_parse_json(repaired)
    if result is not None:
        return result

    arr_match = re.search(r"(\[.*\])", repaired, re.DOTALL)
    if arr_match:
        result = _try_parse_json(arr_match.group(1))
        if result is not None:
            return result

    obj_match = re.search(r"(\{.*\})", repaired, re.DOTALL)
    if obj_match:
        result = _try_parse_json(obj_match.group(1))
        if result is not None:
            return result

    for start_char in ("[", "{"):
        start_idx = repaired.find(start_char)
        if start_idx == -1:
            continue
        truncated = repaired[start_idx:]
        lines = truncated.split('\n')
        for trim_count in range(min(len(lines), 12)):
            candidate_lines = lines[:len(lines) - trim_count] if trim_count > 0 else lines
            candidate = '\n'.join(candidate_lines)
            candidate = re.sub(r',\s*$', '', candidate.rstrip())
            open_braces = candidate.count('{') - candidate.count('}')
            open_brackets = candidate.count('[') - candidate.count(']')
            suffix = ']' * max(0, open_brackets) + '}' * max(0, open_braces)
            if suffix or trim_count > 0:
                attempt = candidate + suffix
                result = _try_parse_json(attempt)
                if result is not None:
                    return result
                attempt_repaired = _repair_json_string(attempt)
                result = _try_parse_json(attempt_repaired)
                if result is not None:
                    return result

    logger.warning("All JSON extraction attempts failed on LLM output length: %d", len(text))
    return None


def _normalize_option_letter(val: Any, valid_set: tuple = ("a", "b", "c")) -> str:
    if val is None:
        return valid_set[0]
    s = str(val).strip().lower()
    if s in valid_set:
        return s
    if "x" in valid_set and any(k in s for k in ("kein", "nein", "none", "nicht", "x")):
        return "x"
    m = re.search(r"\b([a-z])\b", s)
    if m and m.group(1) in valid_set:
        return m.group(1)
    if s and s[0] in valid_set:
        return s[0]
    return valid_set[0]


def _extract_item_answer(item: Dict[str, Any], default: str = "a", valid_options: tuple = ("a", "b", "c")) -> str:
    raw = (
        item.get("answer_key")
        or item.get("answer")
        or item.get("correct_answer")
        or item.get("solution")
        or item.get("correct_option")
        or item.get("correct")
        or default
    )
    return _normalize_option_letter(raw, valid_set=valid_options)


def _normalize_options_dict(raw_opts: Any) -> Dict[str, str]:
    if isinstance(raw_opts, list):
        return {chr(ord('a') + i): str(opt) for i, opt in enumerate(raw_opts[:3])}
    elif isinstance(raw_opts, dict):
        normalized = {}
        for k, v in raw_opts.items():
            norm_key = _normalize_option_letter(k, valid_set=("a", "b", "c"))
            normalized[norm_key] = str(v)
        for k in ("a", "b", "c"):
            if k not in normalized:
                normalized[k] = f"Option {k.upper()}"
        return normalized
    return {"a": "Option A", "b": "Option B", "c": "Option C"}


def _sanitize_mcq_items(
    items_raw: List[Dict],
    id_start: int,
    count: int = 5,
    valid_options: tuple = ("a", "b", "c")
) -> Tuple[List[Dict], Dict, Dict]:
    sanitized_items = []
    answer_key = {}
    explanations = {}

    for idx, item in enumerate(items_raw[:count], start=id_start):
        q_id = idx
        ans = _extract_item_answer(item, default=valid_options[0], valid_options=valid_options)
        exp = str(item.get("explanation") or item.get("reason") or "Richtige Antwort laut Text.")

        if valid_options == ("a", "b", "c"):
            opts = _normalize_options_dict(item.get("options", {}))
            sanitized_items.append({
                "id": q_id,
                "question": str(item.get("question", "")),
                "options": opts
            })
        else:
            sanitized_items.append({
                "id": q_id,
                "question": str(item.get("question", ""))
            })

        answer_key[str(q_id)] = ans
        explanations[str(q_id)] = exp

    return sanitized_items, answer_key, explanations


# ---------------------------------------------------------------------------
# LLM Question Generation Functions (Called via External Metal LLM)
# ---------------------------------------------------------------------------

async def _generate_questions_for_text(
    text: str,
    teil_type: str,
    num_questions: int = 5,
    id_start: int = 1,
    max_retries: int = 2,
) -> List[Dict[str, Any]]:
    """Prompt the external LLM to generate multiple-choice questions for a given German text."""
    id_end = id_start + num_questions - 1
    prompt = (
        f"You are creating Goethe-Zertifikat A2 Reading comprehension questions.\n"
        f"Read this German {teil_type}:\n\n"
        f"{text}\n\n"
        f"Create exactly {num_questions} multiple-choice questions numbered {id_start} to {id_end} about the text above.\n"
        f"Each question must have 3 options ('a', 'b', 'c'), an 'answer_key' ('a', 'b', or 'c'), and a German 'explanation'.\n"
        f"Return ONLY a valid JSON array matching this structure:\n"
        f"[\n"
        f'  {{"id": {id_start}, "question": "Frage auf Deutsch?", "options": {{"a": "Option A", "b": "Option B", "c": "Option C"}}, "answer_key": "a", "explanation": "Erklärung laut Text."}}\n'
        f"]"
    )

    for attempt in range(1, max_retries + 1):
        try:
            raw = await asyncio.wait_for(
                asyncio.to_thread(generate_external, prompt, 800, 0.2),
                timeout=90.0
            )
            parsed = _extract_json(raw)
            items = None
            if isinstance(parsed, list):
                items = parsed
            elif isinstance(parsed, dict):
                items = parsed.get("items") or parsed.get("questions")

            if items and len(items) >= 1:
                logger.info("Generated %d questions on attempt %d for %s", len(items), attempt, teil_type)
                # Pad to num_questions if needed
                while len(items) < num_questions:
                    pad_id = id_start + len(items)
                    items.append({
                        "id": pad_id,
                        "question": f"Was wird im Text zu Punkt {pad_id} gesagt?",
                        "options": {"a": "Wichtige Information", "b": "Zusätzliches Detail", "c": "Keine Angabe"},
                        "answer_key": "a",
                        "explanation": "Laut Text ist diese Information korrekt."
                    })
                return items[:num_questions]
            else:
                logger.warning("Attempt %d for %s returned insufficient items (%d)", attempt, teil_type, len(items) if items else 0)
        except Exception as e:
            logger.warning("Attempt %d error generating questions for %s: %s", attempt, teil_type, e)

    # Fallback to prevent exam generation from crashing
    logger.warning("Using fallback questions for %s", teil_type)
    fallback_items = []
    for i in range(num_questions):
        q_id = id_start + i
        fallback_items.append({
            "id": q_id,
            "question": f"Was ist laut Text für Frage {q_id} richtig?",
            "options": {"a": "Aussage A aus dem Text", "b": "Aussage B", "c": "Aussage C"},
            "answer_key": "a",
            "explanation": "Erklärung laut dem bereitgestellten Text."
        })
    return fallback_items


# ---------------------------------------------------------------------------
# Lesen Teile (Hybrid: Pool Text + LLM-generated Questions)
# ---------------------------------------------------------------------------

async def generate_lesen_teil1(level: str = "A2") -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Lesen Teil 1: Newspaper Article from certified pool + LLM generated questions."""
    pool = _get_text_pool()
    text_data = pool.get_random_text("lesen_teil1")

    items_raw = await _generate_questions_for_text(
        text=text_data["text"],
        teil_type="newspaper article",
        num_questions=5,
        id_start=1,
    )
    sanitized_items, answer_key, explanations = _sanitize_mcq_items(items_raw, id_start=1)

    sanitized = {
        "teil": 1,
        "title": text_data.get("title", "Lesen Teil 1: Zeitungsartikel"),
        "text": text_data["text"],
        "items": sanitized_items,
        "source": "hybrid"
    }
    return sanitized, {"answer_key": answer_key, "explanations": explanations}


async def generate_lesen_teil2(level: str = "A2") -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Lesen Teil 2: Floor Directory from pool + LLM generated customer scenarios."""
    pool = _get_text_pool()
    text_data = pool.get_random_text("lesen_teil2")

    directory_text = ""
    for floor in text_data.get("directory", []):
        directory_text += f"{floor['floor']}: {floor['departments']}\n"

    items_raw = await _generate_questions_for_text(
        text=directory_text,
        teil_type="department store floor directory",
        num_questions=5,
        id_start=6,
    )
    sanitized_items, answer_key, explanations = _sanitize_mcq_items(items_raw, id_start=6)

    sanitized = {
        "teil": 2,
        "title": text_data.get("title", "Lesen Teil 2: Kaufhaus-Wegweiser"),
        "directory": text_data["directory"],
        "items": sanitized_items,
        "source": "hybrid"
    }
    return sanitized, {"answer_key": answer_key, "explanations": explanations}


async def generate_lesen_teil3(level: str = "A2") -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Lesen Teil 3: Personal Email from pool + LLM generated comprehension questions."""
    pool = _get_text_pool()
    text_data = pool.get_random_text("lesen_teil3")

    email_full_text = (
        f"Von: {text_data.get('sender', 'Anna')}\n"
        f"An: {text_data.get('recipient', 'Freund/Freundin')}\n"
        f"Betreff: {text_data.get('subject', 'Neuigkeiten')}\n\n"
        f"{text_data['text']}"
    )

    items_raw = await _generate_questions_for_text(
        text=email_full_text,
        teil_type="personal email",
        num_questions=5,
        id_start=11,
    )
    sanitized_items, answer_key, explanations = _sanitize_mcq_items(items_raw, id_start=11)

    sanitized = {
        "teil": 3,
        "title": text_data.get("title", "Lesen Teil 3: E-Mail / Brief"),
        "sender": text_data.get("sender", "Anna"),
        "recipient": text_data.get("recipient", "Freund/Freundin"),
        "subject": text_data.get("subject", "Neuigkeiten"),
        "text": text_data["text"],
        "items": sanitized_items,
        "source": "hybrid"
    }
    return sanitized, {"answer_key": answer_key, "explanations": explanations}


async def generate_lesen_teil4(level: str = "A2") -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Lesen Teil 4: Classified Ads from pool + LLM generated person-matching questions."""
    pool = _get_text_pool()
    text_data = pool.get_random_text("lesen_teil4")

    ads_text = ""
    for ad in text_data.get("ads", []):
        ads_text += f"Anzeige {ad['id'].upper()}: {ad['title']} - {ad['text']}\n\n"

    prompt = (
        f"Read these 6 classified ads:\n\n{ads_text}\n"
        "Generate 5 questions (IDs 16 to 20). Each question describes a person looking for something specific in German.\n"
        "The person must match EXACTLY ONE ad (answer_key 'a'-'f'), or NO ad (answer_key 'x').\n"
        "At least 3 questions must match an ad. At least 1 question must be 'x' (no match).\n"
        "Return ONLY a valid JSON array:\n"
        "[\n"
        '  {"id": 16, "question": "Personenbeschreibung auf Deutsch...", "answer_key": "b", "explanation": "Erklärung..."},\n'
        '  {"id": 17, "question": "Personenbeschreibung auf Deutsch...", "answer_key": "d", "explanation": "Erklärung..."},\n'
        '  {"id": 18, "question": "Personenbeschreibung auf Deutsch...", "answer_key": "a", "explanation": "Erklärung..."},\n'
        '  {"id": 19, "question": "Personenbeschreibung auf Deutsch...", "answer_key": "f", "explanation": "Erklärung..."},\n'
        '  {"id": 20, "question": "Personenbeschreibung auf Deutsch...", "answer_key": "x", "explanation": "Keine Anzeige passt."}\n'
        "]"
    )

    items_raw = None
    for attempt in range(1, 3):
        try:
            raw = await asyncio.wait_for(
                asyncio.to_thread(generate_external, prompt, 800, 0.2),
                timeout=90.0
            )
            parsed = _extract_json(raw)
            if isinstance(parsed, list) and len(parsed) >= 1:
                items_raw = parsed
                break
            elif isinstance(parsed, dict) and "items" in parsed:
                items_raw = parsed["items"]
                break
        except Exception as e:
            logger.warning("Teil 4 question generation attempt %d error: %s", attempt, e)

    if not items_raw:
        logger.warning("Using fallback for Lesen Teil 4")
        items_raw = [
            {"id": 16, "question": "Herr Becker sucht ein günstiges Fahrrad.", "answer_key": "a", "explanation": "Anzeige A bietet Fahrräder an."},
            {"id": 17, "question": "Frau Klein möchte am Wochenende wandern gehen.", "answer_key": "b", "explanation": "Anzeige B bietet Wanderungen an."},
            {"id": 18, "question": "Thomas sucht eine Wohnung in der Stadtmitte.", "answer_key": "c", "explanation": "Anzeige C bietet Wohnungen an."},
            {"id": 19, "question": "Sarah möchte Spanisch lernen.", "answer_key": "d", "explanation": "Anzeige D bietet Sprachkurse an."},
            {"id": 20, "question": "Familie Meyer sucht ein Segelboot für den Urlaub.", "answer_key": "x", "explanation": "Keine Anzeige passt zu Segelbooten."}
        ]

    valid_options = ("a", "b", "c", "d", "e", "f", "x")
    sanitized_items, answer_key, explanations = _sanitize_mcq_items(
        items_raw, id_start=16, valid_options=valid_options
    )

    sanitized = {
        "teil": 4,
        "title": text_data.get("title", "Lesen Teil 4: Anzeigen & Personen"),
        "ads": text_data["ads"],
        "items": sanitized_items,
        "source": "hybrid"
    }
    return sanitized, {"answer_key": answer_key, "explanations": explanations}


# ---------------------------------------------------------------------------
# Schreiben Teile (External LLM Generation)
# ---------------------------------------------------------------------------

async def generate_schreiben_teil1(level: str = "A2") -> Dict[str, Any]:
    """Generate Schreiben Teil 1 (Informal SMS / Note) using external LLM."""
    fallback_choice = _pick_distinct_pool_item(POOL_SCHREIBEN_TEIL1, "schreiben_t1")
    try:
        template = load_prompt("exam_schreiben_teil1.txt")
        raw = await asyncio.wait_for(
            asyncio.to_thread(generate_external, template, 512, 0.7),
            timeout=45.0
        )
        parsed = _extract_json(raw)
        if parsed and "scenario_german" in parsed and "bullet_points" in parsed and len(parsed["bullet_points"]) >= 2:
            parsed["source"] = "llm"
            return parsed
        fallback_copy = dict(fallback_choice)
        fallback_copy["source"] = "fallback"
        return fallback_copy
    except Exception as e:
        logger.warning("Schreiben Teil 1 using fallback: %s", e)
        fallback_copy = dict(fallback_choice)
        fallback_copy["source"] = "fallback"
        return fallback_copy


async def generate_schreiben_teil2(level: str = "A2") -> Dict[str, Any]:
    """Generate Schreiben Teil 2 (Formal Email) using external LLM."""
    fallback_choice = _pick_distinct_pool_item(POOL_SCHREIBEN_TEIL2, "schreiben_t2")
    try:
        template = load_prompt("exam_schreiben_teil2.txt")
        raw = await asyncio.wait_for(
            asyncio.to_thread(generate_external, template, 512, 0.7),
            timeout=45.0
        )
        parsed = _extract_json(raw)
        if parsed and "scenario_german" in parsed and "bullet_points" in parsed and len(parsed["bullet_points"]) >= 2:
            parsed["source"] = "llm"
            return parsed
        fallback_copy = dict(fallback_choice)
        fallback_copy["source"] = "fallback"
        return fallback_copy
    except Exception as e:
        logger.warning("Schreiben Teil 2 using fallback: %s", e)
        fallback_copy = dict(fallback_choice)
        fallback_copy["source"] = "fallback"
        return fallback_copy


# ---------------------------------------------------------------------------
# Fallback Pools for Schreiben
# ---------------------------------------------------------------------------

POOL_SCHREIBEN_TEIL1: List[Dict[str, Any]] = [
    {
        "teil": 1,
        "title": "Schreiben Teil 1: Verspätung ankündigen",
        "scenario_german": "Sie haben sich heute Abend mit Ihrem Freund Michael im Kino verabredet, können aber nicht pünktlich sein.",
        "instructions_german": "Schreiben Sie eine kurze Nachricht an Michael (ca. 20–30 Wörter). Schreiben Sie zu allen drei Punkten:",
        "bullet_points": ["Entschuldigen Sie sich für die Verspätung.", "Nennen Sie den Grund.", "Schlagen Sie einen neuen Treffpunkt oder eine neue Uhrzeit vor."],
        "target_word_count": "20–30 Wörter",
        "tips_english": "Write a short SMS/note (approx. 20-30 words). Address all 3 bullet points."
    },
    {
        "teil": 1,
        "title": "Schreiben Teil 1: Einladung ablehnen",
        "scenario_german": "Ihre Kollegin Maria hat Sie zum Abendessen am Freitag eingeladen. Sie haben aber leider keine Zeit.",
        "instructions_german": "Schreiben Sie eine kurze Nachricht an Maria (ca. 20–30 Wörter). Schreiben Sie zu allen drei Punkten:",
        "bullet_points": ["Bedanken Sie sich für die Einladung.", "Erklären Sie, warum Sie nicht kommen können.", "Schlagen Sie ein Treffen am nächsten Wochenende vor."],
        "target_word_count": "20–30 Wörter",
        "tips_english": "Write a short note (approx. 20-30 words). Thank, give reason, propose alternative."
    },
    {
        "teil": 1,
        "title": "Schreiben Teil 1: Sporttraining absagen",
        "scenario_german": "Sie trainieren regelmäßig mit Ihrem Freund Lukas im Fitnessstudio, sind heute aber krank.",
        "instructions_german": "Schreiben Sie eine Nachricht an Lukas (ca. 20–30 Wörter). Schreiben Sie zu allen drei Punkten:",
        "bullet_points": ["Sagen Sie das Training für heute ab.", "Erklären Sie kurz Ihren Grund.", "Vereinbaren Sie einen neuen Termin."],
        "target_word_count": "20–30 Wörter",
        "tips_english": "Write an informal note (20-30 words) cancelling training, stating why, and rescheduling."
    }
]

POOL_SCHREIBEN_TEIL2: List[Dict[str, Any]] = [
    {
        "teil": 2,
        "title": "Schreiben Teil 2: Sprachkurs anfragen",
        "scenario_german": "Sie möchten im nächsten Monat einen Deutschkurs (Stufe B1) besuchen. Schreiben Sie an die Sprachschule.",
        "instructions_german": "Schreiben Sie eine formelle E-Mail an Frau Weber (ca. 30–40 Wörter). Schreiben Sie zu allen vier Punkten:",
        "bullet_points": ["Grund für Ihr Schreiben nennen", "Nach Kurstermin und Beginn fragen", "Nach Kosten und Unterkünften fragen", "Formelle Anrede und Grußformel"],
        "target_word_count": "30–40 Wörter",
        "tips_english": "Write a formal email (30-40 words). Address all points with formal greetings."
    },
    {
        "teil": 2,
        "title": "Schreiben Teil 2: Zimmerreservierung",
        "scenario_german": "Sie möchten mit Ihrer Familie zwei Zimmer im Hotel 'Alpenblick' buchen.",
        "instructions_german": "Schreiben Sie eine formelle E-Mail an das Hotel (ca. 30–40 Wörter). Schreiben Sie zu allen vier Punkten:",
        "bullet_points": ["Ankunftstag und Personenzahl nennen", "Nach Frühstück und Zimmerpreisen fragen", "Nach Parkplätzen fragen", "Höfliche formelle Schlussformel"],
        "target_word_count": "30–40 Wörter",
        "tips_english": "Write a formal hotel reservation email."
    },
    {
        "teil": 2,
        "title": "Schreiben Teil 2: Wohnungsbesichtigung",
        "scenario_german": "Sie haben eine Anzeige für eine 2-Zimmer-Wohnung gesehen und möchten die Wohnung besichtigen.",
        "instructions_german": "Schreiben Sie eine E-Mail an den Vermieter Herrn Müller (ca. 30–40 Wörter). Schreiben Sie zu allen vier Punkten:",
        "bullet_points": ["Sich kurz vorstellen", "Interesse an der Wohnung bekunden", "Nach einem Besichtigungstermin fragen", "Formelle Grußformel verwenden"],
        "target_word_count": "30–40 Wörter",
        "tips_english": "Write a formal apartment inquiry email."
    }
]
