{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inference-ingress-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lang-learn.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: public
  rules:
    - host: {{ .Values.ingress.inferenceHost | default "inference.langlearn.local" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lang-learn-inference-predictor
                port:
                  number: 80
{{- end }}
