apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi

  storageClassName: microk8s-hostpath
