"""llama-cpp-python inference backend (GGUF Gemma 2B).

Used on Linux/KServe where MLX (Apple Metal) is unavailable.
Loads the 2B model for all tasks (dialog, word explainer, exam questions).

Set via environment variable:
  LANG_LEARN_MODEL_PATH → path to the .gguf model file
"""
from __future__ import annotations

import logging
import os
import threading
from typing import Iterable

# pyrefly: ignore [missing-import]
from ..config import MAX_TOKENS, MODEL_PATH, TEMPERATURE

logger = logging.getLogger("lang_learn.backends.llamacpp")

# ---------------------------------------------------------------------------
# Single model instance
# ---------------------------------------------------------------------------
_llm = None
_lock = threading.Lock()


def _get_llm():
    global _llm
    if _llm is None:
        with _lock:
            if _llm is None:
                # pyrefly: ignore [missing-import]
                from llama_cpp import Llama

                n_threads = int(os.getenv("LANG_LEARN_N_THREADS", "4"))
                if n_threads < 4:
                    n_threads = 4
                logger.info("Loading model (2B): %s", MODEL_PATH)
                _llm = Llama(
                    model_path=MODEL_PATH,
                    n_ctx=4096,
                    n_threads=n_threads,
                    verbose=False,
                )
                logger.info("Model loaded successfully")
    return _llm


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def warmup() -> None:
    """Pre-load the GGUF model into memory."""
    logger.info("Warming up model...")
    _get_llm()
    logger.info("Model ready")


def generate(
    prompt: str,
    images: Iterable[str] | None = None,  # noqa: ARG001 — not supported by llama.cpp
    max_tokens: int = MAX_TOKENS,
    temperature: float = TEMPERATURE,
) -> str:
    """Generate text using the 2B model."""
    llm = _get_llm()
    with _lock:
        output = llm.create_chat_completion(
            messages=[{"role": "user", "content": prompt}],
            max_tokens=max_tokens,
            temperature=temperature,
        )
    return output["choices"][0]["message"]["content"]


def generate_stream(
    prompt: str,
    max_tokens: int = MAX_TOKENS,
    temperature: float = TEMPERATURE,
) -> Iterable[str]:
    """Stream tokens from the 2B model.

    Yields each token string as it is generated by the model.
    """
    llm = _get_llm()
    stream = llm.create_chat_completion(
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=temperature,
        stream=True,
    )
    for chunk in stream:
        delta = chunk["choices"][0].get("delta", {})
        token = delta.get("content", "")
        if token:
            yield token
