apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lang-learn-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rickdevma100/lang-learn-mlops
    targetRevision: main
    path: infra/argocd

    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
